CREATE TABLE `transferdepartment` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `AGRG_PYMT_AMT` bigint(20) NOT NULL,
 `CNTRY_EN_NM` varchar(150) DEFAULT NULL,
 `CTY_EN_NM` varchar(150) DEFAULT NULL,
 `DEPT_EN_DESC` varchar(150) DEFAULT NULL,
 `DEPARTMENTNUMBER` bigint(20) NOT NULL,
 `FSCL_YR` varchar(150) DEFAULT NULL,
 `MINC` bigint(20) NOT NULL,
 `MINE` varchar(250) DEFAULT NULL,
 `PROVTER_EN` varchar(250) DEFAULT NULL,
 `RCPNT_CLS_EN_DESC` varchar(250) DEFAULT NULL,
 `RCPNT_NML_EN_DESC` varchar(250) DEFAULT NULL,
 `TOT_CY_XPND_AMT` bigint(20) NOT NULL DEFAULT '0',
 PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19453 DEFAULT CHARSET=latin1